version: '3'
services:
  react:
    container_name: react
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    # volumes:
    #   - app:/app
    # command: [ "npm", "run", "dev" ]
    networks:
      - net
  
    
volumes:
  app:

networks:
  net: